name: "Self-Hosted Runner"

on:
  workflow_dispatch:
    secrets:
      tenant_id:
        required: true
      service_principal_client_id:
        description: 'The service principal client ID'
        required: true
      service_principal_client_secret:
        description: 'The service principal client secret'
        required: true

jobs:
  build-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: az login
        run: |
          az login --tenant ${{ secrets.tenant_id }} \
            --service-principal \
            -u ${{ secrets.service_principal_client_id }} \
            -p ${{ secrets.service_principal_client_secret }}

      - name: Replace tokens
        run: |
          sed -i "s/replacetoken/${{ secrets.runnertoken }}/g" scripts/install-runner.sh
          sed -i "s#replacerepo#Oddjob62/self_hosted_runner#g" scripts/install-runner.sh
          sed -i "s/replacelabel/production/g" scripts/install-runner.sh
          ls -l
          cat install-runner.sh

      - name: Build Runner VM
        run: |
          subnetId=$(az network vnet subnet show -g $RUNNER_RG -n "default" --vnet-name "vnet1" -o tsv --query "id")

          az vm create -g $RUNNER_RG \
            -n "TestRunner" \
            --size Standard_B2ms \
            --assign-identity "[system]" \
            --image UbuntuLTS \
            --ssh-key-value id_rsa.pub \
            --admin-username adminuser \
            --custom-data ./scripts/install-runner.sh \
            --subnet $subnetId \
            --nic-delete-option delete \
            --os-disk-delete-option delete \
            --nsg ""

        env:
          RUNNER_RG: SelfhostedTest

