name: "Self-Hosted Runner"

on:
  workflow_dispatch:
    secrets:
      tenant_id:
        required: true
      service_principal_client_id:
        description: 'The service principal client ID'
        required: true
      service_principal_client_secret:
        description: 'The service principal client secret'
        required: true
      gh_pat:
        description: 'The Github access token'
        required: true

env:
  RUNNER_RG: SelfhostedTest
  VNET_NAME: vnet1
  
jobs:
  build-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: az login
        run: |
          az login --tenant ${{ secrets.tenant_id }} \
            --service-principal \
            -u ${{ secrets.service_principal_client_id }} \
            -p ${{ secrets.service_principal_client_secret }}
            
      - name: Build Foundation
        run: |
          az group create -l uksouth -n $RUNNER_RG
          az network vnet create --address-prefixes 10.0.0.0/16 -n $VNET_NAME -g $RUNNER_RG  --subnet-name default --subnet-prefixes 10.0.0.0/24

      - name: Get Token
        id: get-token
        run: |
          echo ${{ secrets.gh_pat }} | gh auth login --with-token
          token=$(gh api -X POST -H "Accept: application/vnd.github.v3+json" /repos/$GITHUB_REPOSITORY/actions/runners/registration-token | jq .token -r)
          echo "::set-output name=runnertoken::$token"

      - name: Replace tokens
        run: |
          sed -i "s/replacetoken/${{ steps.get-token.outputs.runnertoken }}/g" scripts/install-runner.sh
          sed -i "s#replacerepo#Oddjob62/self_hosted_runner#g" scripts/install-runner.sh
          sed -i "s/replacelabel/production/g" scripts/install-runner.sh
          ls -l

      - name: Build Runner VM
        run: |
          subnetId=$(az network vnet subnet show -g $RUNNER_RG -n "default" --vnet-name $VNET_NAME -o tsv --query "id")

          az vm create -g $RUNNER_RG \
            -n "TestRunner" \
            --size Standard_B2ms \
            --assign-identity "[system]" \
            --image 20_04-lts \
            --ssh-key-value id_rsa.pub \
            --admin-username adminuser \
            --custom-data ./scripts/install-runner.sh \
            --subnet $subnetId \
            --nic-delete-option delete \
            --os-disk-delete-option delete \
            --nsg ""



